### PR TITLE
Added pubkey authentication handler

### LINKED ISSUE #42: Exploring other kinds of auth issues
Based on the rsylog config (and I am guessing the parsing code in the container), am I right in thinking that this will only detect the bad password type of error: ```Failed password for username from 206.253.167.10 port 11111 ssh2```

but not these:
```
May 18 14:09:57 moebius sshd[24830]: Invalid user bob from 72.xx.xx.87 port 38124
May 18 14:09:57 moebius sshd[24830]: input_userauth_request: invalid user bob [preauth]
May 18 14:09:57 moebius sshd[24830]: userauth_pubkey: key type ssh-dss not in PubkeyAcceptedKeyTypes [preauth]
May 18 14:09:57 moebius sshd[24830]: userauth_pubkey: key type ssh-dss not in PubkeyAcceptedKeyTypes [preauth]
May 18 14:09:57 moebius sshd[24830]: Connection closed by 72.xx.xx.87 port 38124 [preauth]
May 18 14:10:09 moebius sshd[24847]: userauth_pubkey: key type ssh-dss not in PubkeyAcceptedKeyTypes [preauth]
May 18 14:10:09 moebius sshd[24847]: userauth_pubkey: key type ssh-dss not in PubkeyAcceptedKeyTypes [preauth]
May 18 14:10:10 moebius sshd[24847]: Connection closed by 72.xx.xx.87 port 38126 [preauth]
```

That may be more common, since it's best practice to use ssh keys instead of passwords?

### PR DESCRIPTION
**Pull request by acouvreur**
Simple way to capture authentication fails when the PasswordAuthentication is disabled. Which is my case.

### CODE REVIEW

**Comment by edasque** [comment]
I pulled this branch and it works well when it's a wrong user but doesn't if the right key isn't provided. This is what the auth.log looks like when that happens:
```
2020-05-19 10:32:31 | May 19 14:32:31 moebius sshd[13766]: Connection closed by 72.84.19.87 port 57092 [preauth]
2020-05-19 10:32:31 | May 19 14:32:31 moebius sshd[13766]: userauth_pubkey: key type ssh-dss not in PubkeyAcceptedKeyTypes [preauth]
2020-05-19 10:32:31 | May 19 14:32:31 moebius sshd[13766]: userauth_pubkey: key type ssh-dss not in PubkeyAcceptedKeyTypes [preauth]
```

I imagine you'd have to look at multiple lines in this case. You can maybe use the ssh client port number (13766 for this particular interactions) to see if the last message which holds the IP was due to a bad key illustrated by the prior messages.

Also, a suggestion, if I may. Can you make the rslog code generic whether a key is used or a password? I imagine that you want to be able to identify both on systems where both can be used?

Thank you for your work!

**Comment by acouvreur** [comment]
Yes indeed this is a first draft where I wanted to have things done.

I don't know how this behave when there is PasswordAuthentication and PubkeyAuthentication enabled in terms of logs. I want to avoid duplicates / wrong values.

I'll look into your suggestion, using the "ssh client port" which seems to be the sshd fork process id instead. As the port is mentioned under the first line as 57092. I don't know how to get this information through rsyslog though. As the message starts after the double dots.

**Comment by edasque** [comment]
Ah my bad, PID, you're right, I had wrongly assumed it was the port. Yes, that makes this more difficult. It's probably hard to use the time for this as well.

**Comment by acouvreur** [comment]
I'm going to take a look at these docs https://en.wikibooks.org/wiki/OpenSSH/Logging_and_Troubleshooting#Brute_force_and_Hail_Mary_attacks

Take a look if you can, and if you find something useful let me know.

**Comment by acouvreur** [comment]
With PubkeyAuthentication only, this is the logs I'm getting :

```
May 19 20:51:07 Yggdrasil sshd[16519]: Invalid user mmv from 192.157.233.175 port 33375
May 19 20:51:07 Yggdrasil sshd[16519]: Received disconnect from 192.157.233.175 port 33375:11: Bye Bye [preauth]
May 19 20:51:07 Yggdrasil sshd[16519]: Disconnected from invalid user mmv 192.157.233.175 port 33375 [preauth]
```

I assume that any message that has a [preauth] tag is a subsequent action from the initial request. In my case the fact that an invalid user tries to login.

I'll need to enable PasswordAuthentication to see what happens in the logs...

**Comment by acouvreur** [comment]
With PasswordAuthentication
```
Mar 18 18:55:05 server sshd[38594]: Invalid user ubnt from 201.179.249.231 port 52471
Mar 18 18:55:05 server sshd[38594]: Failed password for invalid user ubnt from 201.179.249.231 port 52471 ssh2
Mar 18 18:55:09 server sshd[38594]: error: maximum authentication attempts exceeded for invalid user ubnt from 201.179.249.231 port 52471 ssh2 [preauth]
Mar 18 18:55:09 server sshd[38594]: Disconnecting invalid user ubnt 201.179.249.231 port 52471: Too many authentication failures [preauth]
```

Both 'Failed...' and 'Invalid...' messages appears, so maybe I should catch 'Failed' messages anymore ? And only using 'Invalid' messages ?

**Pull request merged**
